title: David Lu
description: Gas dynamics, rocket propulsion, blueberry muffins.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
baseurl: "/blueberrymuffins"
github:
  zip_url: /blueberrymuffins/publications
